kind: pipeline
type: exec
name: default

steps:

  - name: build
    commands:
      - sudo docker build . -t stanbic-server-${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    when:
      branch:
        - main

  - name: deploy
    commands:
      - sudo docker container stop stanbic-server
      - sudo docker container rm stanbic-server
      - sudo docker run --name stanbic-server -d  -p 4100:8080 stanbic-server-${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    when:
      branch:
        - main
